import { execa } from "execa";
import { log } from "./log.js";
import type { TaskRecord } from "./types.js";

export interface PrCreateInput {
  cwd: string; // a worktree on the run branch (or the main repo)
  baseBranch: string; // 'main'
  headBranch: string; // 'DOCH-AUTORUN-7'
  title: string;
  bodyHtml: string; // we'll convert to MD-ish for gh
  draft?: boolean;
}

// gh accepts plain text or markdown for body. Build a Markdown body from the
// run summary + per-task list, since Plane comments are HTML and PR descriptions
// usually want Markdown.
export interface PrBodyInput {
  identifierPrefix: string;
  runBranch: string;
  succeeded: TaskRecord[];
  blocked: TaskRecord[];
  conflicts: TaskRecord[];
  totalCostUsd: number;
  startedAt: number;
  endedAt: number;
}

export function buildPrBody(input: PrBodyInput): string {
  const dur = ((input.endedAt - input.startedAt) / 60_000).toFixed(0);
  const lines: string[] = [];
  lines.push(`## Autorun ${input.runBranch}`);
  lines.push("");
  lines.push(
    `**Summary:** ${input.succeeded.length} succeeded · ${input.blocked.length} blocked · ${input.conflicts.length} merge conflict — \$${input.totalCostUsd.toFixed(2)} · ${dur}m`,
  );
  lines.push("");

  if (input.succeeded.length > 0) {
    lines.push("### Succeeded");
    lines.push("");
    for (const t of input.succeeded) {
      lines.push(`- **${t.identifier}** — ${t.title}`);
      if (t.summary) lines.push(`  - ${t.summary}`);
    }
    lines.push("");
  }
  if (input.conflicts.length > 0) {
    lines.push("### Successful but unmerged (merge conflict)");
    lines.push("");
    for (const t of input.conflicts) {
      lines.push(`- **${t.identifier}** — ${t.title} (branch: \`${t.subBranch}\`)`);
    }
    lines.push("");
  }
  if (input.blocked.length > 0) {
    lines.push("### Blocked");
    lines.push("");
    for (const t of input.blocked) {
      lines.push(`- **${t.identifier}** — ${t.title}`);
      if (t.summary) lines.push(`  - ${t.summary}`);
    }
    lines.push("");
  }
  lines.push("---");
  lines.push("");
  lines.push("Generated by plane-autorun. See `runs.db` for full details.");
  return lines.join("\n");
}

export async function createDraftPr(input: PrCreateInput): Promise<string> {
  const args = [
    "pr",
    "create",
    "--base",
    input.baseBranch,
    "--head",
    input.headBranch,
    "--title",
    input.title,
    "--body",
    input.bodyHtml,
  ];
  if (input.draft ?? true) args.push("--draft");
  log.info({ baseBranch: input.baseBranch, headBranch: input.headBranch }, "creating draft PR");
  const r = await execa("gh", args, { cwd: input.cwd });
  // gh prints the URL on stdout.
  const url = r.stdout.trim().split("\n").pop() ?? "";
  if (!/^https?:\/\//.test(url)) {
    throw new Error(`gh pr create did not return a URL; output was: ${r.stdout}`);
  }
  return url;
}
